services:
  # --- AWS Emulator (LocalStack) ---
  localstack:
    image: localstack/localstack:3.8.1
    container_name: localstack
    ports:
      - "4566:4566"            # Edge port for all AWS services
      - "4510-4559:4510-4559"  # Port range for external services (like Lambda)
    environment:
      - SERVICES=s3,lambda,iam,logs,sts
      - DEBUG=0
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - ENFORCE_IAM=true
    volumes:
      # Save temporary files of localstack
      - localstack-data:/var/lib/localstack
      # Required for Localstack to spawn containers running Lambda code
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Folder containing shell scripts to configure resources when LocalStack is ready
      - "./localstack/init:/etc/localstack/init/ready.d"
      # Mount raw dataset for scripts or Lambda to read and write during initialization
      - "./data/raw:/data/raw"
      # Mount ClickHouse config to update IAM key
      - "./clickhouse/config:/opt/clickhouse-config"
      # Mount code lambda
      - "./lambdas:/opt/lambdas"
    networks:
      - youtube-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Analytical Database (ClickHouse) ---
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"            # HTTP port (Connect HTTP / PowerBI)
      - "9000:9000"            # Native TCP port (clickhouse-client)
    volumes:
      # Configuration file for S3 connection with LocalStack
      - "./clickhouse/config/s3_storage.xml:/etc/clickhouse-server/config.d/s3_storage.xml"
      # Automatically run scripts to create schema/tables when DB is initialized
      - "./clickhouse/init:/docker-entrypoint-initdb.d"
      # Store ClickHouse data
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=youtube_analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse123
      - CLICKHOUSE_AWS_ACCESS_KEY_ID=${CLICKHOUSE_AWS_ACCESS_KEY_ID}
      - CLICKHOUSE_AWS_SECRET_ACCESS_KEY=${CLICKHOUSE_AWS_SECRET_ACCESS_KEY}
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - youtube-net

  # --- Airflow Metadata Database ---
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data
    networks:
      - youtube-net

  # --- Airflow DB Init (Run once to create tables and admin account) ---
  airflow-init:
    image: apache/airflow:2.7.2-python3.10
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"
    networks:
      - youtube-net
    user: "${AIRFLOW_UID:-50000}:0"

  # --- Airflow Webserver (UI Port 8080) ---
  airflow-webserver:
    image: apache/airflow:2.7.2-python3.10
    container_name: airflow-webserver
    depends_on:
      - postgres
      - airflow-init
      - localstack
    environment:
      - LOAD_EX=nym  # Disable default Airflow example DAGs
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AWS_ENDPOINT_URL=http://localstack:4566
      - LOCALSTACK_ENDPOINT=http://localstack:4566  # Point upload_to_landing endpoint to localstack container
    command: webserver
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./.env:/opt/airflow/.env
      - ./airflow/logs:/opt/airflow/logs  # Mount shared log folder
      - ./data:/opt/airflow/data  # Mount data for upload_to_landing to read raw data
    ports:
      - "8080:8080"
    networks:
      - youtube-net
    user: "${AIRFLOW_UID:-50000}:0"

  # --- Airflow Scheduler ---
  airflow-scheduler:
    image: apache/airflow:2.7.2-python3.10
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - airflow-init
      - localstack
    environment:
      - LOAD_EX=nym
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AWS_ENDPOINT_URL=http://localstack:4566
      - LOCALSTACK_ENDPOINT=http://localstack:4566  # Point upload_to_landing endpoint to localstack container
    command: scheduler
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./.env:/opt/airflow/.env
      - ./airflow/logs:/opt/airflow/logs  # Mount shared log folder
      - ./data:/opt/airflow/data  # Mount data for upload_to_landing to read raw data
    networks:
      - youtube-net
    user: "${AIRFLOW_UID:-50000}:0"

volumes:
  localstack-data:
  clickhouse-data:
  airflow-db-data:

networks:
  youtube-net:
    driver: bridge
